-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회하는 SQL문

SELECT T_OUNTS.ANIMAL_ID, T_OUNTS.NAME
FROM ANIMAL_OUTS AS T_OUNTS
    LEFT JOIN ANIMAL_INS AS T_INS
    ON T_OUNTS.ANIMAL_ID = T_INS.ANIMAL_ID  
WHERE T_INS.ANIMAL_ID IS NULL 
; 